# Generated by Django 6.0.4 on 2026-05-07 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_auxiliary_contact_product_coil_voltage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='gst_price',
        ),
    ]
