# Generated by Django 4.2.7 on 2026-04-17 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_b2brequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='b2brequest',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='login.user'),
        ),
    ]
