# Generated by Django 6.0.4 on 2026-05-07 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
