# Generated by Django 6.0.4 on 2026-05-08 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0002_enquiry_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
