# Generated by Django 6.0.4 on 2026-05-07 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
